---
title: "Prerequisites"
author: "Jonathan Navarrete"
date: ""
output: 
  ioslides_presentation:
    theme: readable
    smaller: true
    wide: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Welcome | Setting Up R

Before getting started there are a few things you'll need in order to be successful in the course

- A recent version of [R](https://cran.r-project.org/)

I am currently using version 3.4.0 on Ubuntu

- A recent version of [RStudio](https://www.rstudio.com/products/rstudio/download/)

I am currently using version 1.0.143


## Welcome | Setting Up Python

A recent version of Python 3

- [Anaconda](https://conda.io/miniconda.html)

- [Enthought Canopy](https://store.enthought.com/downloads/)

- [Python](https://www.python.org/)

Jupyter Notebook environment

- [IPython notebooks](https://nbviewer.jupyter.org/github/ipython/ipython/blob/4.0.x/examples/IPython%20Kernel/Index.ipynb)

- `pip install jupyter`

- `conda install jupyter`

- `conda install ipython`




## Welcome | Setting Up Python pt. 2

Scientific python stack

- `conda install numpy` (easiest)

- `pip install numpy` (may be problematic on Windows)

Enthought Canopy has it's owns package manager as well. Point and click.

Spyder IDE

- `conda install spyder`

Enthought Canopy comes with an IDE that allows you to open up IPython Notebooks.

[Using Jupyter (IPython) Notebooks in Canopy](https://support.enthought.com/hc/en-us/articles/204469580-Using-Jupyter-IPython-Notebooks-in-Canopy)



## Welcome | Setting Up 

- A web browser like Firefox (any OS), Chrome (any OS) or Microsoft Edge (Windows 10)

- (Optional) StackExchange [Cross Validated](https://stats.stackexchange.com/) account

Feel free to ask lookup, ask and answer questions on Cross Validated


## Optional References

No textbook is necessary to follow with the course!

1. For Monte Carlo methods: [Introducing Monte Carlo Methods with R](https://www.amazon.com/Introducing-Monte-Carlo-Methods-Use/dp/1441915753)
  - Read reviews before making any purchases!
  
2. For statistics and probability review: [Introduction to Probability Models, Tenth Edition](https://www.amazon.com/Introduction-Probability-Models-Tenth-Sheldon/dp/0123756863/ref=sr_1_9?s=books&ie=UTF8&qid=1502653034&sr=1-9)

The course follows the layout of work by Christian Robert & George Casella.

